all: main.c read_input_files.c print_functions.c basic_functions.c scheduler.c linked_list_functions.c
	gcc -Da -o main main.c read_input_files.c print_functions.c basic_functions.c scheduler.c linked_list_functions.c -I.
