WORKLOAD=$1
WORKLOAD_TP=${WORKLOAD:27}
CLUSTER=$2
CLUSTER_TP=${CLUSTER:24}
CLUSTER_TP=${CLUSTER_TP::-4}
echo ${WORKLOAD_TP}
echo ${CLUSTER_TP}

python3 src/Compute_area_ratio_previous_CONVERTED_WORKLOAD.py ${WORKLOAD} ${CLUSTER}
