all: ipdps

ipdps:
	rm -f *.toc *.aux *.log *.out *.blg *.xml *.dvi *.bbl *.bcf *.ist *glsdefs *.lof *.acn *.glo *.nav *.snm
	pdflatex ipdps.tex
	pdflatex ipdps.tex
	rm -f *.toc *.aux *.log *.out *.blg *.xml *.dvi *.bbl *.bcf *.ist *glsdefs *.lof *.acn *.glo *.nav *.snm
	
uppmax:
	rm -f *.toc *.aux *.log *.out *.blg *.xml *.dvi *.bbl *.bcf *.ist *glsdefs *.lof *.acn *.glo *.nav *.snm
	pdflatex uppmax.tex
	pdflatex uppmax.tex
	rm -f *.toc *.aux *.log *.out *.blg *.xml *.dvi *.bbl *.bcf *.ist *glsdefs *.lof *.acn *.glo *.nav *.snm
	
clean:
	rm -f *.toc *.aux *.log *.out *.blg *.xml *.dvi *.bbl *.bcf *.ist *glsdefs *.lof *.acn *.glo *.nav *.snm

.SILENT: pdf

