all: main.c read_input_files.c print_functions.c basic_functions.c scheduler.c linked_list_functions.c backfill_functions.c scheduler_calling.c
	gcc -std=c99 -Wall -O3 -DPRINT -o main main.c read_input_files.c print_functions.c basic_functions.c scheduler.c linked_list_functions.c backfill_functions.c scheduler_calling.c energy_incentive_functions.c -I. -lm

clean:
	rm *.o
